### ISSUE TITLE
Internet Explorer logo

### ISSUE THREAD

**Issue by jakub300** [alrra/browser-logos#100]
Hey, I've noticed that you moved IE logos to archive recently. There are [hundreds of projects](https://github.com/search?p=2&q=raw+alrra+internet-explorer&ref=searchresults&type=Code&utf8=%E2%9C%93) that refer to that logo by its old URL. Are you sure that you want to break all of them?

**Comment by alrra** [comment]
> There are hundreds of projects that refer to that logo by its old URL. Are you sure that you want to break all of them?

@jakub300 The recommended ways of getting these logos are listed under the [`Getting the browser logos`]( https://github.com/alrra/browser-logos/tree/12aa960021445b76eb901b949dbcffdbe9addc9e#getting-the-browser-logos) section from the main [`README.md`]( https://github.com/alrra/browser-logos/tree/12aa960021445b76eb901b949dbcffdbe9addc9e#readme) file.

Changes are specified in detail in the [`CHANGELOG.md`](https://github.com/alrra/browser-logos/blob/12aa960021445b76eb901b949dbcffdbe9addc9e/CHANGELOG.md) [files](https://github.com/alrra/browser-logos/search?utf8=%E2%9C%93&q=filename%3ACHANGELOG.md&type=Code) as well as in every [release](https://github.com/alrra/browser-logos/releases).

Linking directly to `master` is never a good idea, and if one does so, she/he assumes the risk of things breaking at any time.

**Comment by scribblemaniac** [comment]
For the curious here is a list of the top 1000 results from the search "raw alrra", sorted by stars:
[BrokenLogos.txt](https://github.com/alrra/browser-logos/files/668242/BrokenLogos.txt)

Upon closer inspection, it seems that a service called [BrowserStack](https://www.browserstack.com/) may be to blame for the majority of these broken links.
