### ISSUE TITLE
Update Maxthon icon

### ISSUE THREAD

**Issue by ngyikp** [alrra/browser-logos#104]
Not sure why Maxthon is on the archive, they actually released version 5 just 2 months ago, and this seems to be their new logo (I extracted it directly from Maxthon.exe)

![maxthon](https://cloud.githubusercontent.com/assets/6135313/21559275/48ded6b2-ce84-11e6-8197-768e8352657b.png)

ICO: [maxthon icon.zip](https://github.com/alrra/browser-logos/files/678215/maxthon.icon.zip)

**Comment by alrra** [comment]
> Not sure why Maxthon is on the archive, 

@ngyikp That is because that logo is the one used by an older version of the Maxthon browser.

**Comment by alrra** [comment]
@ngyikp Thanks for bringing this up!

**Comment by scribblemaniac** [comment]
@alrra Where did you get that 960x960 logo from?

**Comment by alrra** [comment]
> Where did you get that 960x960 logo from?

@scribblemaniac From [here](http://www.maxthon-fr.com/forum/uploads/monthly_10_2016/post-3-0-84595100-1476703446.png).
