### ISSUE TITLE
Package information is missing for puffin

### ISSUE THREAD

**Issue by janpapenbrock** [alrra/browser-logos#108]
Changelog, package.json and README are missing for Puffin browser.

See [src/puffin](https://github.com/alrra/browser-logos/tree/6f328628858bc9f9ff4cb19f09365a84b70c55e8/src/puffin).

**Comment by janpapenbrock** [comment]
Actually on quite a few others in archive as well (e.g. 360-secure, adrenaline, airweb, allinone, amigo, apollo), from my random clicking. Is this on purpose?

**Comment by alrra** [comment]
> Is this on purpose? 

Yes. From https://github.com/alrra/browser-logos/issues/99#issue-187682357:

> Logos for which the exact browser versions are not known won't be published as that can potentially create confusion and some problems down the line.

**Comment by janpapenbrock** [comment]
Just found that as well :) Alright. What is the recommended way for these? Download the full package?

**Comment by alrra** [comment]
> What is the recommended way for these? Download the full package?

Either copy them manually, or use any of the options listed under [`2) Get all logos`](https://github.com/alrra/browser-logos/tree/3bb26173c9c2b861c1d19b49bb397cdf3cd03ff1#2-get-all-logos) section from the [`README.md`](https://github.com/alrra/browser-logos/blob/3bb26173c9c2b861c1d19b49bb397cdf3cd03ff1/README.md) file.

**Comment by janpapenbrock** [comment]
Alright, thank you for your work and the quick reply!

**Comment by alrra** [comment]
> whether it's worth taking out of the archive

@dandv [This logo](https://github.com/alrra/browser-logos/blob/94860625086d80228263f5dcf42f58af2507bbce/src/archive/360-secure/360-secure.png) is in the archive because it is no longer used by the latest versions of the `360 secure` browser.

I'll happily accept a PR with the logo currently used by `360 secure` (but do note that it has to be at least `512x512px`).
