### ISSUE TITLE
Add svg logo for internet explorer 9-11

### ISSUE THREAD

**Issue by mkxml** [alrra/browser-logos#117]
It would be cool to have the SVG version of the legacy internet-explorer 9-11 logo.

We could use this one: [Wikimedia IE 9 logo](https://upload.wikimedia.org/wikipedia/commons/1/1b/Internet_Explorer_9_icon.svg)

Though it doesn't look **exactly** like the PNGs.

Let me know what you think.

**Comment by alrra** [comment]
> We could use this one: Wikimedia IE 9 logo

Unfortunately, that SVG is not even close to the [official logo](https://github.com/alrra/browser-logos/blob/09c098833d43a35d95805178f11401fb66153eea/src/archive/internet-explorer_9-11/internet-explorer_9-11.png). :(

> It would be cool to have the SVG version of the legacy internet-explorer 9-11 logo.

It would be nice, but unfortunately no one contributed it yet. Closest we got was a [`.eps`](https://github.com/alrra/browser-logos/pull/48#issuecomment-46688515).  If you, or anyone else can convert the `.eps` file to a decent `.svg`, I'll gladly accept that pull request.
