### ISSUE TITLE
Update Firefox Nightly icon

### ISSUE THREAD

**Issue by ngyikp** [alrra/browser-logos#122]
https://twitter.com/FirefoxNightly/status/893577526009880576

<img width="512" alt="" src="https://user-images.githubusercontent.com/6135313/28992126-0929ae86-79c7-11e7-9f59-a4e08d5e88d1.png">

[firefox.icns.zip](https://github.com/alrra/browser-logos/files/1202035/firefox.icns.zip)

**Comment by alrra** [comment]
Thanks, @ngyikp!
