### ISSUE TITLE
Library license

### ISSUE THREAD

**Issue by sashberd** [alrra/browser-logos#133]
Hi @alrra ,
Under what license you library is hosted?
Thanks

**Comment by alrra** [comment]
See https://github.com/alrra/browser-logos#legal and https://github.com/alrra/browser-logos/issues/83.

**Comment by sashberd** [comment]
@alrra I saw the legal, and I understand that icons are under owner license... But you code is under MIT?

**Comment by alrra** [comment]
> But you code is under MIT?

Yes, everything else is MIT (I should specify that).
