### ISSUE TITLE
Please update to the latest Brave logo

### ISSUE THREAD

**Issue by Jacalz** [alrra/browser-logos#135]
Please update the Brave logo to the latest version from here:
https://www.brave.com/about/images/brave_icon_512x.png

**Comment by alrra** [comment]
@Jacalz Do you have a SVG version of the logo?

Also, if you know, can you also provide the version of Brave when this logo started to be used?

Thanks!

**Comment by Jacalz** [comment]
Sorry I don’t know what version they were new in and I don’t have an svg version. But I am a moderator on Brave community, collaborator on github and I also know the designer so I will ask him 🙂

**Comment by alrra** [comment]
> Sorry I don’t know what version they were new

@Jacalz No problem, if at one point you find out, let me know!

> and I don’t have an svg version

It seems the site contain one: https://brave.com/fonts/brave_logo_horz_reversed.svg. 

---

I'll update the logo when I have some free time.

Thanks for opening this issue! 💜

**Comment by Jacalz** [comment]
Great but that svg you used is reversed 😅 The shading is the other way around, I did just get the svgs for you if you want 🙂

**Comment by alrra** [comment]
> Sorry, but that svg you used is reversed 😅 The shading is the other way around

I got it from the official website. 😕

![](https://user-images.githubusercontent.com/1223565/34909323-debb4fcc-f853-11e7-9431-862a0c69f8f2.png)

> I did just get the svgs for you if you want 🙂

Sure.

**Comment by Jacalz** [comment]
I am sorry but the logos I got are the ones that will be in the next release 0.20.x, that is why they are not in the website 😉 They are a bit more red and has not gradient 🙂 I am sorry that I did not say it earlier 😔

**Comment by alrra** [comment]
> Sorry, but that svg you used is reversed 😅 The shading is the other way around

I just downloaded latest Brave and the shading is in the right spot. :/

![](https://user-images.githubusercontent.com/1223565/34909370-78a0930e-f854-11e7-8555-13012a21a3e7.png)

**Comment by alrra** [comment]
> I am sorry but the logos I got are the ones that will be in the next release 0.20.x, that is why they are not in the website 😉 They are a bit more red and has not gradient 🙂 I am sorry that I did not say it earlier 😔

Ok. When the logo get's updated, feel free to open another issue. Thanks!

**Comment by Jacalz** [comment]
Oh yeah, will do then 😉
