### ISSUE TITLE
Update Brave logos to the current version as of 0.20.x

### ISSUE THREAD

**Issue by Jacalz** [alrra/browser-logos#136]
The Brave logos were updated to a more flatter look with a slightly different shade of orange with the 0.20.x release. Those new icons will come with the next ios version too.

Here are the SVG files for it:
[brave_logos_SVG.zip](https://github.com/alrra/browser-logos/files/1691582/brave_logos_SVG.zip)

**Comment by alrra** [comment]
> The Brave logos were updated to a more flatter look with a slightly different shade of orange with the 0.20.x release. 

@Jacalz The current Brave logo looks different than what you provided in `brave_logos_SVG.zip`.

| Current logo | Logo from<br>`brave_logos_SVG.zip` |
|:---:|:---:|
|  <img src="https://user-images.githubusercontent.com/1223565/35789062-4a421b1c-09ee-11e8-9c2e-3a2d9a3119a2.png" width=300> |  <img src="https://user-images.githubusercontent.com/1223565/35789235-b3aee156-09ef-11e8-838d-119bdf6b4281.png" width=300> |

[](https://github.com/alrra/browser-logos/files/1693879/brave.svg.zip)

<img src="https://user-images.githubusercontent.com/1223565/35789101-88c88f88-09ee-11e8-96db-a32c191662f6.png" width=300>

**Comment by alrra** [comment]
@Jacalz Actually, look the same in Chrome, but not in Firefox.

**Comment by Jacalz** [comment]
They look the same for me at least and they look very different from the old one 👍

**Comment by alrra** [comment]
> they look very different from the old one 👍

Yes.

> They look the same for me at least and  

The version of the logo used by the current version of Brave (v0.20.30) and the SVG version of the logo you provided are a bit different.

Here is a diff between them:

<img width="326" src="https://user-images.githubusercontent.com/1223565/35893491-28daef50-0b63-11e8-8d55-06943a078b62.png">

And in case there is a problem with something else (e.g.: image color profiles) here is a picture of the previous comment:

![](https://user-images.githubusercontent.com/1223565/35893622-d21be10a-0b63-11e8-807d-ac0719b207ca.jpg)

**Comment by alrra** [comment]
@Jacalz I ended up using https://brave.com/fonts/brave_logo_2color_reversed.svg, as it seems it didn't have the problem specified above.

Thanks again for opening this issue!

**Comment by Jacalz** [comment]
Thanks a lot 👍

**Comment by alrra** [comment]
@Jacalz Do you know if there is a SVG version of [`Brave Dev`](https://brave.com/download-dev/)? Thanks!

**Comment by Jacalz** [comment]
I don't really know, couldn't find any SVG version for it but I will ask to see if I can get one...

**Comment by Jacalz** [comment]
Here you go @alrra 👍 [brave_dev.zip](https://github.com/alrra/browser-logos/files/2393623/brave_dev.zip)

**Comment by alrra** [comment]
Thank you, @Jacalz!
