### ISSUE TITLE
Add `basilisk` browser logo

### ISSUE THREAD

**Issue by KonoromiHimaries** [alrra/browser-logos#137]
![](https://www.basilisk-browser.org/bas-logo-300w.png)

**Comment by alrra** [comment]
@KonoromiHimaries Do you know if there is a more decent version (`512⨯512px` or higher), or an SVG version of the logo? Thanks!

**Comment by scribblemaniac** [comment]
@KonoromiHimaries Added in 43643afeb48341733454f46eb220ae72192f4751. :)
