### ISSUE TITLE
Safari logo missing SVG version

### ISSUE THREAD

**Issue by shayc** [alrra/browser-logos#138]
Awesome project! I noticed the Safari logo is missing the SVG version.

**Comment by alrra** [comment]
> I noticed the Safari logo is missing the SVG version.

@shayc Unfortunately, no one has yet found or created a SVG version of the Safari logo that is the same as the official one. 😔

---

See also: #88, #132.

**Comment by shayc** [comment]
Alright, I just found out this logo, it's not pixel perfect but very close (and good for my usage):
https://worldvectorlogo.com/logo/safari-3

**Comment by alrra** [comment]
> Alright, I just found out this logo, it's not pixel perfect but very close (and good for my usage):
https://worldvectorlogo.com/logo/safari-3

That is the [same one as the one from this comment](https://github.com/alrra/browser-logos/pull/88#issuecomment-252885636).

> and good for my usage

:+1:
