### ISSUE TITLE
@Latest

### ISSUE THREAD

**Issue by polyma** [alrra/browser-logos#139]
Hello,

Great repo, very helpful! 

I noticed on the CDN that you have strict versioning for all the logos. I myself really just want to display the most recent logo for each browser, I can imagine that would be a pretty common use case for others too. Would it be possible to have a /latest/ version on the CDN?

**Comment by alrra** [comment]
> I noticed on the CDN that you have strict versioning for all the logos...
>
> Would it be possible to have a /latest/ version on the CDN?

@polyma If that feature doesn't exists, there is nothing this repository can do about it. You should open an issue in the [`cdnjs`](https://github.com/cdnjs/cdnjs) repository (if one doesn't exists already).

See also: https://github.com/alrra/browser-logos/issues/83.

Also, Cc @PeterDaveHello.

>  I myself really just want to display the most recent logo for each browser,

There are sometimes breaking changes (e.g.: the path changes as logos are moved to the archive, they are renamed, etc.), so relying on the `/latest/` is not a good long term solution.

**Comment by scribblemaniac** [comment]
BTW, cndnjs does have many many issues on this feature already, [this one](https://github.com/cdnjs/cdnjs/issues/360) being the primary issue. Considering how long it has been open and how many people have requested it, I would not hold my breath for it to be implemented any time soon.

**Comment by PeterDaveHello** [comment]
Sorry that that's something that CDNJS won't and can't implement, the current hosting is directly handled by Cloudflare, and we won't encourage to use it most of the scenarios, to prevent any unpredictable breaking changes, like the removal, renaming of files in the case here or API changes in the other library cases.
