### ISSUE TITLE
Firefox Focus svg doesn't display correctly in Inkscape and Firefox

### ISSUE THREAD

**Issue by Findus23** [alrra/browser-logos#145]
Hi,

I just noticed that the Firefox Focus logo looked odd in my application.

It seems like the svg you are using isn't valid as it doesn't display as it should (and as your `/focus.png` does) when opening in Inkscape.

Even when opening in Firefox (like in the following line), the svg isn't rendered correctly.
<img width="50" src="https://rawgit.com/alrra/browser-logos/master/src/focus/focus.svg">

In case it displays correctly for you, this is how it looks like for me:
<img width="50" src="https://user-images.githubusercontent.com/6266037/39418449-c9798e52-4c5a-11e8-9bc2-e5773c8e5c62.png">

**Comment by alrra** [comment]
> Even when opening in Firefox (like in the following line), the svg isn't rendered correctly.

@Findus23 What version of Firefox are you using?

Everything seems fine to me:

![](https://user-images.githubusercontent.com/1223565/39427732-8dc70208-4c8d-11e8-992d-fa3537f48e27.png)

![](https://user-images.githubusercontent.com/1223565/39427730-8d797bbe-4c8d-11e8-9e51-6596f565f4a9.png)

![](https://user-images.githubusercontent.com/1223565/39427731-8da44d08-4c8d-11e8-85d0-56a0bc00e8bb.png)

**Comment by alrra** [comment]
> I'm also using 59.0.2 (64-Bit) and the file looks like for you.
>
> But shouldn't there be a square purple background like in the .png files?

OK, I thought something was wrong with the SVG.

The reason the SVG is different is because that's how it was provided by Mozilla: https://github.com/FirefoxUX/product-identity, and even thought I wanted to have a SVG version that would be the same as the actual used logo (the PNGs), I decided to include it as I thought that would be beneficial.

A pull request that makes the SVG version the same as the PNGs is very welcomed.

**Comment by scribblemaniac** [comment]
Here's a version of svg made to look like the icon: [focus.svg.zip](https://github.com/alrra/browser-logos/files/1962313/focus.svg.zip)

Although it becomes clear when comparing them that the svg we have right now is not quite the same as what is used in the icon. Most notably the inside circle is way too bright.

Focus Icon | SVG
:---: | :---:
![focus_512x512](https://user-images.githubusercontent.com/3461051/39452706-680a1750-4c90-11e8-8838-7010d06a6cce.png) | ![focus-export](https://user-images.githubusercontent.com/3461051/39452709-6e55a958-4c90-11e8-88ed-8ef5aebbc3f0.png)

**Comment by alrra** [comment]
@Findus23 @scribblemaniac I've open an [issue](https://github.com/FirefoxUX/product-identity/issues/9), let's see if they provide an official one.
