### ISSUE TITLE
V8 logos with white outline (for use on dark backgrounds)

### ISSUE THREAD

**Issue by mathiasbynens** [alrra/browser-logos#152]
Not sure if this project is interested in them, but V8 now has outlined versions of each logo: https://v8.dev/logo

**Comment by alrra** [comment]
> Not sure if this project is interested in them

The project contains [Edge beta for light and dark background](https://github.com/alrra/browser-logos/blob/e46c926cc408e2abcbca916a9fca1bede843ef15/src/README.md#edge) so, yes, it make sense to have them.
