### ISSUE TITLE
Add `Brave Nightly` logo

### ISSUE THREAD

**Issue by alrra** [alrra/browser-logos#168]
<img width="250" alt="Brave Nightly browser logo" src="https://user-images.githubusercontent.com/1223565/54860008-415cfe00-4cd1-11e9-82e6-b0cd31cb2f4f.png">

Ref: https://brave.com/download-nightly/

**Comment by alrra** [comment]
👆🏻 @Jacalz

**Comment by alrra** [comment]
@Jacalz Can you help with the SVG version of the logo? Thanks!

**Comment by Jacalz** [comment]
I will see what I can do and get back to you when I get something
