### ISSUE TITLE
IE11 logo incorrect

### ISSUE THREAD

**Issue by Rykus0** [alrra/browser-logos#171]
The IE11 logo is all blue and doesn't have the yellow like IE9 did

**Comment by Findus23** [comment]
I am not sure what you are referring to, but `src/archive/internet-explorer_9-11/internet-explorer_9-11.png` does have "the yellow"
![](https://raw.githubusercontent.com/alrra/browser-logos/master/src/archive/internet-explorer_9-11/internet-explorer_9-11.png)

**Comment by Rykus0** [comment]
You're right, I really wasn't clear.  Sorry about that - that's what I get for rushing.  

The IE11 logo I've seen does not have the yellow, whereas the one you have here does.  Maybe both are correct?

![image](https://user-images.githubusercontent.com/1745718/58726373-92fbc600-83af-11e9-80a1-c0f60a2fe2fd.png)

**Comment by alrra** [comment]
From what I remember that icon / logo is only used in the about page, and over time is seems it wasn't even used consistently. 

e.g.: [image search for IE 10](https://www.google.com/search?q=ie+10&source=lnms&tbm=isch) (that also has it for certain versions):

![](https://user-images.githubusercontent.com/1223565/58763362-88a40e00-850e-11e9-8b23-0383a94b3f6d.png)

![](https://user-images.githubusercontent.com/1223565/58763363-88a40e00-850e-11e9-9bce-8fd9a31533ff.jpg)

But the logo/icon used in all other places in Windows (desktop, taskbar, etc.) was always the same one, [the one that is included in this repository](https://github.com/alrra/browser-logos/tree/180f2c33c07e83645fa64ea6097f0aa9d1fadd58/src/archive/internet-explorer_9-11).

---

![](https://user-images.githubusercontent.com/1745718/58726373-92fbc600-83af-11e9-80a1-c0f60a2fe2fd.png)


@Rykus0 If you (or someone else) can find some official information about it / it's usage, and can provide a good reason to include it, I will consider its inclusion. Thanks!

**Comment by Rykus0** [comment]
Interesting, thanks!  I guess I'd mostly seen the updated logo, but I see the desktop icon I have is the one with the yellow.  

Thanks for following up on this, and for putting this great resource together

**Comment by zaharovalex1107-debug** [comment]
IE dies 2022
