### ISSUE TITLE
Add new Firefox logos

### ISSUE THREAD

**Issue by alrra** [alrra/browser-logos#172]
Ref: https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand/

**Comment by mathiasbynens** [comment]
Per <https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand/#comment-6369>:

> > Oh yeah, and SVG files for the new logos would also be appreciated. Thanks! :-)
>
> We’re putting the final touches on a brand website. Access to logos is weeks away!

**Comment by mathiasbynens** [comment]
https://mozilla.design/firefox/logos-usage/

**Comment by mathiasbynens** [comment]
Sounds like the Firefox browser logo won’t be changing, and the new logo refers to something else.

**Comment by alrra** [comment]
> Sounds like the Firefox browser logo won’t be changing, and the new logo refers to something else.

@mathiasbynens Interesting. 

---

> Ref: https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand/
<img width="726" src="https://user-images.githubusercontent.com/1223565/60391558-00317280-9aa6-11e9-8031-4789f4d4d1ff.png">

It seems [they did make some](https://github.com/mozilla-mobile/fenix/issues/868#issuecomment-483376700) versions of the logos in the new style:

<img width="500" alt="New Firefox Preview logo" src="https://user-images.githubusercontent.com/1223565/60391496-6917eb00-9aa4-11e9-973b-cacf3026c7ea.png">
<img width="500" alt="New Firefox Nightly Preview logo" src="https://user-images.githubusercontent.com/1223565/60391497-69b08180-9aa4-11e9-9d9b-8ef9d54c22b1.png">


---

Also, they have released [Firefox Preview](https://play.google.com/store/apps/details?id=org.mozilla.fenix) that is in the new style.

![Firefox Preview](https://user-images.githubusercontent.com/1223565/60391606-1b50b200-9aa7-11e9-8b65-bb0dcfb9ef36.png)

**Comment by mathiasbynens** [comment]
This is confusing.

[The "Firefox browser logos" section](https://mozilla.design/firefox/logos-usage/) (can't directly link there since it lacks an `id`) seems like the canonical source of truth, and it still contains the current browser logos, which would indicate no changes.

**Comment by alrra** [comment]
> The "Firefox browser logos" section (can't directly link there since it lacks an id) seems like the canonical source of truth, and it still contains the current browser logos, which would indicate no changes.

@callahad  ⬆️

**Comment by callahad** [comment]
Sorry for the confusion.
The logo above is _not yet_ the official Firefox Browser logo, though it will turn into that before this time next year.
Basically, the official logo hasn't changed until you see the new icon in your dock. :)

**Comment by alrra** [comment]
> it will turn into that before this time next year.
> Basically, the official logo hasn't changed until you see the new icon in your dock. :)

@callahad Thank you for clarifying, I sincerely appreciate it!

---

> it will turn into that before this time next year.

Since it's going to take a while, I'm going to close this issue for now.

Note: I've added [Firefox Preview](https://github.com/alrra/browser-logos/blob/3cf99413cc8a16398abd0360fcdc2950fc1a466d/src/README.md#firefox-preview) and [GeckoView](https://github.com/alrra/browser-logos/blob/3cf99413cc8a16398abd0360fcdc2950fc1a466d/src/README.md#geckoview).

**Comment by alrra** [comment]
Ref: https://twitter.com/FirefoxNightly/status/1160829707853717505?s=09

**Comment by callahad** [comment]
If this follows [the normal release schedule](https://wiki.mozilla.org/RapidRelease/Calendar), expect the new logo would be in all channels by the time Firefox 70 is released on October 22nd.

**Comment by alrra** [comment]
> It seems [they did create some](https://github.com/mozilla-mobile/fenix/issues/868#issuecomment-483376700) versions of the logos in the new style:

[Updated the `Firefox Nightly` logo](https://github.com/alrra/browser-logos/commit/e1e5b57141cf221c9421af0d22b68ee95e1d6a62).

---

> If this follows the normal release schedule, expect the new logo would be in all channels by the time Firefox 70 is released on October 22nd.

@callahad Can you help provide the SVG versions of the new logos once they become available? Thanks!

**Comment by callahad** [comment]
I'll poke around and see if I can find standalone files for just the logos, but for now, SVGs of the wordmarks, which include the logos, are available at: [Nightly](https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/branding/nightly/content/horizontal-lockup.svg), [DevEdition](https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/branding/aurora/content/horizontal-lockup.svg), [Release](https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/branding/official/content/horizontal-lockup.svg)

**Comment by alrra** [comment]
@callahad Thank you!

**Comment by alrra** [comment]
@callahad If you find the SVG versions for the [other logos](https://github.com/alrra/browser-logos/blob/master/src/README.md#firefox) (e.g.: Firefox Beta), please let me know!

Also, once again, thank you for your help, I sincerely appreciate it! 🙇🏻‍♂️

**Comment by alrra** [comment]
@callahad, @shorlander Are there SVG versions for Firefox Beta and [Firefox Lite](https://github.com/alrra/browser-logos/tree/0f5be42e52234db1b2212dc2a98fbc87b2604d28/src/firefox-lite#firefox-lite)? Thank you!

---

![Firefox Beta logo](https://user-images.githubusercontent.com/1223565/64352224-7ecbf400-cfb0-11e9-9427-e8912196c093.png)
