### ISSUE TITLE
Update Tor Browser's Icon

### ISSUE THREAD

**Issue by Zhai2333** [alrra/browser-logos#174]
Tor Browser now have a new icon.
It looks like this 👇
![Tor Browser on macOS](https://user-images.githubusercontent.com/21154023/60852934-78c5cb00-a22c-11e9-993c-3a53722c0a2d.png)

**Comment by alrra** [comment]
From https://blog.torproject.org/new-release-tor-browser-85:

![](https://user-images.githubusercontent.com/1223565/60976879-5ba00380-a2e3-11e9-9e2f-2c6e5c9faeb6.png)

**Comment by alrra** [comment]
@Zhai2333 Thank you for opening this issue!
