### ISSUE TITLE
Using the SVG inline in HTML distorts colors due to shared IDs

### ISSUE THREAD

**Issue by zwergius** [alrra/browser-logos#177]
So using 4 of these browser-logos inline in html distort the colors of all but the first one.

This is caused by all gradient id's not being unique, which is a requirement to use these inline in html.

<img width="423" alt="Screenshot 2019-09-26 at 09 03 35" src="https://user-images.githubusercontent.com/2060308/65666223-7ca00700-e03d-11e9-9db2-40ab2a85a755.png">

**Comment by alrra** [comment]
@zwergius Sorry for the delayed answer, this issue just skipped me.

> This is caused by all gradient id's not being unique

This is not an issue with this project per se. This problem will exists with any SVGs that are not vetted / hand crafted by the author of the page they are included in (it's similar to including a bunch of different random 3rd party CSS and expect them to never interfere with each other or with the page's CSS).

---

To overcome this and ensure the scope is preserved, among other, you can use SVG sprites (i.e. `<symbol>` + `<use>`) or custom elements.
