### ISSUE TITLE
Dissenter logo

### ISSUE THREAD

**Issue by boscovn** [alrra/browser-logos#178]
Already got will to whitelist the browser, now it needs the logo https://dissenter.com/
Thank you

**Comment by will-stone** [comment]
By "will" they mean "Will" (me) 😊 @alrra if you don't mind adding the logo of this browser? Linked issue with Browserosaurus: https://github.com/will-stone/browserosaurus/issues/139

**Comment by alrra** [comment]
Thank you for the suggestion!

I will pass on this one for now for the same reasons as the ones specified in [this comment](https://github.com/alrra/browser-logos/pull/157#issuecomment-471230139) (see also: [`CONTRIBUTING.md`](https://github.com/alrra/browser-logos/blob/60644d64dc9dc8b38741d1ac2609a096e68703e8/.github/CONTRIBUTING.md#pull-requests)).

**Comment by will-stone** [comment]
Thanks @alrra. I agree with your logic here; maybe I should take a similar stance for Browserosaurus 🤔
