### ISSUE TITLE
Add new `Edge` logos

### ISSUE THREAD

**Issue by jonathantneal** [alrra/browser-logos#179]
Details pending.

![New Edge browser logo](https://i.imgur.com/6Z9WyCn.png)

**Comment by alrra** [comment]
Ref: https://www.theverge.com/2019/11/2/20944341/microsoft-edge-chromium-browser-logo-icon-wave-surf-new

**Comment by jonathantneal** [comment]
Oh I’m so sorry. When I saw the title I thought I had made a mistake! Then I saw the history. Changed it back. Sorry!

**Comment by jonathantneal** [comment]
https://cdn.vox-cdn.com/uploads/chorus_image/image/65613211/microsoftedgenewlogo.5.jpg

**Comment by jonathantneal** [comment]
PR incoming, courtesy of a generous fellow whom I will credit if they permit me.

**Comment by alrra** [comment]
From https://blogs.windows.com/msedgedev/2019/11/04/edge-chromium-release-candidate-get-ready/#gve7ejwW9tcXVRam.97:

![](https://user-images.githubusercontent.com/1223565/68141703-dddfb380-fee2-11e9-88e7-2ce23a023ee4.png)
