### ISSUE TITLE
CDN doesn't update anymore

### ISSUE THREAD

**Issue by paul-v-m** [alrra/browser-logos#181]
It seems like https://cdnjs.com/libraries/browser-logos is stuck on version 58.1.3.

**Comment by alrra** [comment]
> It seems like https://cdnjs.com/libraries/browser-logos is stuck on version 58.1.3.

@paul-v-m See https://github.com/cdnjs/cdnjs/issues/13524. Hopefully things will get back to normal in the next period, if not, I'll consider removing it as a recommendation.

**Comment by krystian3w** [comment]
Still frozen.

**Comment by alrra** [comment]
Done in https://github.com/alrra/browser-logos/commit/896ab303b43decd25c518ea5dc0081e6974d344a.
