### ISSUE TITLE
Add new Safari logos

### ISSUE THREAD

**Issue by alrra** [alrra/browser-logos#184]
Safari for `macOS Big Sur` comes with a new logo.

<img width="1440" alt="Safari for macOS Big Sur logo"  src="https://user-images.githubusercontent.com/1223565/85481869-8a0c0280-b577-11ea-89e7-3f060a2c0a79.png">

Ref: https://www.youtube.com/watch?v=GEZhD3J89ZE&t=1h19m02s

**Comment by alrra** [comment]
New `Safari Technology Preview` logo:

![New Safari Technology Preview logo:](https://user-images.githubusercontent.com/1223565/85804409-67f0bc80-b6fe-11ea-90e3-ad6ac5eb62b3.png)

**Comment by mathiasbynens** [comment]
@jensimmons, can you help? Is there an official high-res (ideally SVG) version of these logos you can share?

**Comment by gottabeleGIT** [comment]
The new Safari (with the new logo) should also be available on Catalina and Mojave and Apple already has a Catalina build for the latest STP with the new logo

**Comment by gottabeleGIT** [comment]
It seems that `Safari.app` in macOS Big Sur DB 3 has the new icon bundled with it if that helps for extracting the new Safari icon.

**Comment by alrra** [comment]
Thank you, @gottabeleGIT!
