### ISSUE TITLE
Add Lossless WebP Support

### ISSUE THREAD

**Issue by nick-botticelli** [alrra/browser-logos#188]
According to [Can I use](https://caniuse.com/#feat=webp), at least 80% of all internet users currently use browsers that support the lossless WebP image format. WebP consistently provides lower file sizes and also reportedly [decodes faster than PNG](https://developers.google.com/speed/webp/docs/webp_lossless_alpha_study).

For example, encoding the chrome_128x128.png image in this repository to a lossless WebP (using cwebp) results in no image differences (i.e. completely lossless) and a ~24% reduction in file size (12,226 bytes vs. 9,278 bytes).

The last major browser that currently does not support WebP is Safari, with support coming for Safari on iOS 14 and macOS Big Sur. Operating systems such as Android 4.2+ and Windows 10 also support the lossless WebP format.

With this considered, I believe it would be beneficial to add support for lossless WebP in this repo.

**Comment by alrra** [comment]
@nick-botticelli Thank you for taking the time to open this issue!
---

Some [new image formats](https://twitter.com/kornelski/status/1276110256221949952) are being introduced, so I will pass on this for now and will reevaluate this idea at a later time.
