### ISSUE TITLE
Add `Finebits Internet Browser` logo

### ISSUE THREAD

**Issue by scribblemaniac** [alrra/browser-logos#190]
![finebits-internet-browser](https://user-images.githubusercontent.com/3461051/99159505-1f7c7000-269a-11eb-81a6-efdae78fb934.png)
Logo taken from official source here: https://www.microsoft.com/en-us/p/internet-browser/9nblggh3tbjn?activetab=pivot:overviewtab
Notable as one of the only major browsers for the Xbox One (known on the platform as simply "Internet Browser").
I'm not sure if it's being updated or not. Perhaps someone with an Xbox One and this app can weigh in.

**Comment by alrra** [comment]
> I'm not sure if it's being updated or not

Looking a bit into things, it doesn't seem like it has been update in a while.

Also, given that the Xbox One consoles come with Microsoft Edge by default and probably web browsing isn't the main thing people do on that platform, I'll pass on this one.

---

@scribblemaniac  thank you for your suggestion!
