### ISSUE TITLE
new epiphany web browser logo

### ISSUE THREAD

**Issue by linuxcyclist** [alrra/browser-logos#196]
![org gnome Epiphany](https://user-images.githubusercontent.com/82463571/114592193-4db5aa00-9c50-11eb-9f51-46a0636f6cd5.png)
![org gnome Epiphany](https://user-images.githubusercontent.com/82463571/114592293-5e662000-9c50-11eb-95e6-ecdeac2d31a8.png)

**Comment by alrra** [comment]
@linuxcyclist Can you provide more information? I don't really understand what you are referring to.

---

The Web (f.k.a. Epiphany) browser logo has been [recently updated](https://github.com/alrra/browser-logos/blob/9c2870eaa385dee6b87062bcfeec78e70ea59ca5/src/web/CHANGELOG.md#breaking-changes).

See also: https://wiki.gnome.org/Apps/Web.

![Web (f.k.a. Epiphany) new browser logo](https://user-images.githubusercontent.com/1223565/114597979-3b367300-9c46-11eb-8199-5f67e65e9f64.png).
