### ISSUE TITLE
Incorrect version info?

### ISSUE THREAD

**Issue by diverpl** [alrra/browser-logos#197]
After installing the package using npm my `package.json` file looks like this (excerpt):

```
    "dependencies": {
        "apexcharts": "^3.26.0",
        "bootstrap-star-rating": "^4.0.6",
        "browser-logos": "github:alrra/browser-logos",
        "bs-custom-file-input": "^1.3.4",
        "tinymce": "^5.7.1"
    }
```

Version number for browser-logos looks weird. Is this correct?

**Comment by alrra** [comment]
@diverpl Did you run `npm install alrra/browser-logos#70.0.0` ? 

Can you provide more information on what  things you are using (e.g.: what OS,  what `npm` version, etc.)?

Also, is there any reason why you want the whole thing, and not [specific logos](https://github.com/alrra/browser-logos/tree/9c2870eaa385dee6b87062bcfeec78e70ea59ca5#1-get-individual-logos)?

**Comment by alrra** [comment]
> Version number for browser-logos looks weird. Is this correct?

@diverpl Yes. The main package is pretty big so it's not published on `npm`, the suggestion is just for the rare case where people need all the logos. Usually people install / use [specific logos](https://github.com/alrra/browser-logos/tree/9c2870eaa385dee6b87062bcfeec78e70ea59ca5#1-get-individual-logos) (e.g.: npm install `@browser-logos/firefox`).
