### ISSUE TITLE
Add `wexond` logo

### ISSUE THREAD

**Issue by Yash-Singh1** [alrra/browser-logos#199]
@wexond

Wexond is a web browser that is built using `Electron` and `React`

**Comment by alrra** [comment]
@Yash-Singh1 Thank you for the suggestion! 

---

> https://wexond.net/

![](https://user-images.githubusercontent.com/1223565/133736277-408ccf50-358d-4287-93e1-f78e82674611.png)

Closing the issue as the browser is not even released yet.

**Comment by Yash-Singh1** [comment]
I am pretty sure that they didn't update the site yet. The main browser is constantly updated and is already in 5.2.0: https://github.com/wexond/browser-base/releases/tag/v5.2.0.
