### ISSUE TITLE
ie_9-11 SVG very large

### ISSUE THREAD

**Issue by eoghanmurray** [alrra/browser-logos#201]
This SVG includes lots of unnecessary embedded .png <image> dumps to achieve things which can be done with SVG filters etc.

https://github.com/alrra/browser-logos/blob/main/src/archive/internet-explorer_9-11/internet-explorer_9-11.svg

For an idea of the size reduction potential; removing them gets the filesize from 647KB to 77KB albeit with a bit of work to do to get the thing looking correct.

Would a redraw be accepted or is this an official SVG?

**Comment by alrra** [comment]
> This SVG includes lots of unnecessary embedded .png dumps to achieve things which can be done with SVG filters etc.

@eoghanmurray Yes. Unfortunately, when I last tried, I didn't managed to get something that didn't have very noticeable differences.

> SVG filters 

Note: SVG filters are not the best when it comes to performance (see: [[1]](https://inkscape.org/learn/tutorials/avoid-performance-issues/), [[2]](https://www.chromium.org/developers/design-documents/image-filters), [[3]](https://codepen.io/tigt/post/improving-svg-rendering-performance#filter-6)). 

> is this an official SVG?

It is. @docluv provided it for this project when he was working for or with Microsoft (see: https://github.com/alrra/browser-logos/pull/48).

Note: The [`.eps` file is available in the pull request](https://github.com/alrra/browser-logos/pull/48#issuecomment-46688515).

> Would a redraw be accepted 

As long as the differences are not noticeable, yes!

Note: This project often improves upon the original, and when possible, the changes are contributed back to the source  (e.g.: [[1]](https://github.com/v8/v8.dev/pull/170),  [[2]](https://github.com/v8/v8.dev/pull/226), [[3]](https://github.com/v8/v8.dev/pull/263)</sup>, [etc.](https://github.com/v8/v8.dev/search?q=Further+optimize+SVGs&type=issues)).

---

I'm going to close this issue, but as always, pull requests that improve things are very welcomed!

**Comment by eoghanmurray** [comment]
Thanks!

> SVG filters are not always the best when it comes to performance

Suspected this at the back of my mind, but ignored it... good to see the references and I think actually some of the ones I did on the safari SVG could be replaced with radial gradients.

> As long as the differences are not very noticeable, yes!

Is there a way of doing a diff and getting a 'score'?

**Comment by eoghanmurray** [comment]
See #202

**Comment by alrra** [comment]
> Is there a way of doing a diff and getting a 'score'?

@eoghanmurray Yes, see [butteraugli](https://github.com/google/butteraugli).
