### ISSUE TITLE
Add new Chromium and Chrome logos

### ISSUE THREAD

**Issue by alrra** [alrra/browser-logos#206]
From https://twitter.com/elvin_not_11/status/1489647023410212869:

<img alt="New Chrome logos announcement tweet" src="https://user-images.githubusercontent.com/1223565/152694027-a036bd6a-88a4-4dd6-af05-aa3d345a19f5.png" width=650>

---

Logos to update: 

- [x] Chrome
- [x] Chrome Beta
- [x] Chrome Dev
- [x] Chrome DevTools
- [x] Chrome Canary
- [x] Chromium

**Comment by alrra** [comment]
![New Chrome logo](https://user-images.githubusercontent.com/1223565/152899587-8685c681-94f5-4c44-bbf6-8b22de5d58dc.svg)

**Comment by mathiasbynens** [comment]
@alrra, one thing to keep in mind is that in the new logos, the white void gets proportionally thinner at size 128 and above — so it’s not simply a matter of scaling a single logo. I suspect this can still be represented in SVG, perhaps with media queries. Hopefully the official logo assets include an SVG version that captures this accurately.

@elvin-hu, are the new logo assets publicly available (yet)?

**Comment by alrra** [comment]
> one thing to keep in mind is that in the new logos, the white void gets proportionally thinner at size 128 and above — so it’s not simply a matter of scaling a single logo. 

@mathiasbynens Thank you for that information! 

@mathiasbynens It seems the logos will be changed starting with version 100 (or at least that was the case for Canary)? Is that correct?

> Doesn't help that each OS is getting it's own set of logos.

@miquelfire I am not planning to include OS specific ones, so this project will just include the general ones.

**Comment by Alex313031** [comment]
@miquelfire @alrra It would be nice to have OS specific ones for chrome and chromium. I make a chromium browser called Thorium that uses a modified form of the chromium logo, and I build for linux, macos, windows, and chromiumos, so I made logos for all of them by using the svg. If only the general logo is uploaded after M101, then I cant provide a matching differentiation like the upstream chromium project once the logo is completely migrated over for all platforms.

Also, @alrra in response to my previous issue which you closed (very helpful), where did you get the chromium .svg? You provided some nice links for other browsers, but I would specifically like the source for the .svg for chromium. You can find 16px-512px of it in the chromium source, but the .svg is much more useful as it can be upscaled and downscaled, and then converted to a .png for better quality. I couldn't find anywhere else on the net where there is such a high quality .svg of chromium, so I would like to see where you actually got this.

**Comment by alrra** [comment]
> It would be nice to have OS specific ones for chrome and chromium.

@Alex313031 As [previously stated](https://github.com/alrra/browser-logos/issues/206#issuecomment-1032851640), I am not planning to include OS specific logos.

Note: OS specific logos have been used for some time. 

Here is the current Chrome logo on macOS: 

<img src="https://user-images.githubusercontent.com/1223565/154220200-fde927dc-7bbe-458c-bc7a-62e04defea1e.png" width=100> 

vs. the general one:

<img src="https://raw.githubusercontent.com/alrra/browser-logos/main/src/chrome/chrome_512x512.png" width=90>

---

> in response to my previous issue

@Alex313031 Let's keep this issue on topic.

I've [responded](https://github.com/alrra/browser-logos/issues/207#issuecomment-1041218544) to your question in the original issue.

**Comment by argyleink** [comment]
![chrome-beta_64x64](https://user-images.githubusercontent.com/1134620/154383672-cd73a4e5-6e53-476b-897b-f38d2175e78b.png)
![chrome-dev_64x64](https://user-images.githubusercontent.com/1134620/154383675-0427461a-334a-4396-9981-782648e65a48.png)
![chromium_64x64](https://user-images.githubusercontent.com/1134620/154383677-4c6296c9-409b-42db-8091-ec1516a1deb8.png)
![chrome-canary_64x64](https://user-images.githubusercontent.com/1134620/154383678-ca13737c-0d33-4d0d-b5b1-3c2848962015.png)
![chrome_64x64](https://user-images.githubusercontent.com/1134620/154383679-5978d245-0222-4276-bbaa-125345057883.png)

i just spent time making these and realized they were fetched from this repo. maybe my work can help this go easy?

**Comment by alrra** [comment]
> maybe my work can help this go easy?

@argyleink Thank you, but at least a 512x512px PNG version would be needed to cover all the sizes that are provided by this project. :( 

A better solution would be to have the SVG versions of the logos, everything else can be generated based on that. 

I did find [one for the Chrome logo](https://github.com/alrra/browser-logos/issues/206#issuecomment-1032112582) that seems to be pretty close (but do see @mathiasbynens' [comment](https://github.com/alrra/browser-logos/issues/206#issuecomment-1032564575)). 

-----

@argyleink @mathiasbynens @elvin-hu @paulirish Any change Google or the Chrome team can help provide the SVG versions of the logos? Or at least 512x512px PNG versions of them?

**Comment by argyleink** [comment]
here's what i can snag 🙂
![icon-chromium-256](https://user-images.githubusercontent.com/1134620/154389391-eb3a9942-9a3e-464a-8ba9-f029d44824da.svg)
![icon-chrome-stable-256](https://user-images.githubusercontent.com/1134620/154389394-fe46345f-7b62-44a3-87be-4244bb1ed5ad.svg)
![icon-chrome-canary-256](https://user-images.githubusercontent.com/1134620/154389398-b6b58a26-0089-40ff-9fc7-1f821f703952.svg)

**Comment by alrra** [comment]
> here's what i can snag 🙂

@argyleink Woohoo! Thank you! 🙇‍♂️ I will take care of things tonight and release new versions of the packages. 

> It seems the logos will be changed starting with version 100? (or at least that was the case for Canary)

@argyleink Do you know if the above is true?

**Comment by alrra** [comment]
> so it’s not simply a matter of scaling a single logo. I suspect this can still be represented in SVG, perhaps with media queries. Hopefully the official logo assets include an SVG version that captures this accurately.

I'll use the logos [provided](https://github.com/alrra/browser-logos/issues/206#issuecomment-1042489578) by @argyleink for now. But if better versions become available, let me know!

**Comment by alrra** [comment]
> https://github.com/web-platform-tests/wpt.fyi/pull/2744

@argyleink If you update the [`@browser-logos/chrome`](https://www.npmjs.com/package/@browser-logos/chrome), [`@browser-logos/chrome-canary`](https://www.npmjs.com/package/@browser-logos/chrome-canary), and [`@browser-logos/chromium`](https://www.npmjs.com/package/@browser-logos/chromium) packages to `v2.0.0`, they should get the new logos. :)

**Comment by Alex313031** [comment]
@argyleink How did you get the new chromium.svg??? Also @alrra and @argyleink thanks for being so ridiculously quick about this, they literally just added the new chromium logos for linux today, completing the set for different platforms.

**Comment by argyleink** [comment]
> @argyleink How did you get the new chromium.svg??? 

perks of working on the Chrome DevRel team 😄

**Comment by argyleink** [comment]
> @argyleink Do you think you will be able to help with the last 2, namely, Chrome Beta and Dev?

they didnt provide those where i found the assets, i rolled my own in XD

**Comment by Alex313031** [comment]
@argyleink So that svg is an official asset? If so why is it internal? It would make sense to have it in the chromium source, in the resources dir or the chrome/app/theme dir? Also, since you have access to these, is there any way you could get me svgs of the windows, mac, chromiumos, and linux versions (or whichever of those has one that differs from the one here) My browser I make called Thorium uses a modified chromium logo (you can see it right there in my profile pic). I make builds for all of these platforms, and I start with an svg rendered at ultra high resolution, then add the black ring, and then downscale and convert to png and rename for all the files in the chrome/app/theme dir for various platforms. Having an svg of not just the regular one here, but the ones used on these platforms would really help me in making my new iconset for my repo.
If you cant or dont want to, could you at least tell me which ones are different? It appears chromiumos and linux logos are the same as the regular one, but macos has some 3-D at the bottom and is of course in an "app square", and the windows one (supposedly from an article I read on the chrome logo at least) has a very slight gradient across the colours. 

Any info/help related to all of this would be a big help, and I will be adding this repo to the attribution/credits section of my readme (which I should have done from the start when I first used this repo's images in Thorium)

**Comment by Alex313031** [comment]
@argyleink Is the bottom one the windows one? It seems the top is the "normal" one which is the same for linux and chromiumos, whereas the mac obviously has the square around it and is more 3D. The windows one is supposed to have a subtle gradient, and it looks like the bottom one has that gradient vs the top one. Or are they actually in order from what you said i.e. win, then mac, then linux? BTW thanks so much, I didn't know what I was gonna do and thought I would just have to make all platforms use the same one which is undesirable.

**Comment by Alex313031** [comment]
@argyleink Ahh ok that makes sense and is in line with my initial impression.

**Comment by mathiasbynens** [comment]
In line with the new Chrome logos, the Chrome DevTools logo has been updated. It can be found here: https://github.com/ChromeDevTools/devtools-logo/tree/HEAD/logos/svg (The PR was https://github.com/ChromeDevTools/devtools-logo/pull/5.) Note that these SVGs are the canonical versions — they are responsive and change based on the size they’re displayed at. These logos have the following breakpoints:

- Extra small (for display sizes from 1 to 23 pixels)
- Small (for display sizes from 24 to 63 pixels)
- Large (for display sizes from 64 to 127 pixels)
- Extra large (for display sizes ≥ 128 pixels)

I’m working to make the final official responsive SVG versions of the Chrome logos available too.

**Comment by alrra** [comment]
> the Chrome DevTools logo has been updated. It can be found here: https://github.com/ChromeDevTools/devtools-logo/tree/HEAD/logos/svg (The PR was https://github.com/ChromeDevTools/devtools-logo/pull/5.)

@mathiasbynens Thank you, the Chrome DevTools logo has been [updated](https://github.com/alrra/browser-logos/blob/a9b1cbb11b0367f7d39f93712eb7c972a393c51c/src/chrome-devtools/CHANGELOG.md#200-april-6-2022)! 🙇‍♂️

> I’m working to make the final official responsive SVG versions of the other Chrome logos available too.

🎉

**Comment by alrra** [comment]
> I’m working to make the final official responsive SVG versions of the other Chrome logos available too.

@mathiasbynens Do you think you will have time or want to work on it anymore? Thank you! 🙇‍♂️

**Comment by alrra** [comment]
> We finished creating the logos before I posted that message. We're just waiting for the marketing team to officially approve and publish them somewhere.

@mathiasbynens Ok, thank you for the update.

**Comment by alrra** [comment]
> We finished creating the logos before I posted that message. We're just waiting for the marketing team to officially approve and publish them somewhere.

@mathiasbynens Any updates on this? Thank you!

**Comment by alrra** [comment]
> > We finished creating the logos before I posted that message. We're just waiting for the marketing team to officially approve and publish them somewhere.
>
> @mathiasbynens Any updates on this? Thank you!

[Chrome logo](https://github.com/web-platform-dx/baseline-status/pull/30#issuecomment-2451693918)
