### ISSUE TITLE
Chromium Logos and sources.

### ISSUE THREAD

**Issue by Alex313031** [alrra/browser-logos#207]
I saw the issue regarding the chrome logo, just reminding you to do chromium too. I make my own Chromium fork for linux, win, and macos called Thorium > https://github.com/Alex313031/Thorium/ And I used your chromium svg as a starting point for editing the logo in gimp to make the thorium logo. I rendered it at 8192x8192, added black to the inner ring, and then exported as .png to the various sizes needed for the the logo in the chromium source code for various platforms. So thanks for this project. I also used the webview-dev icon for content_shell, which is something I added to the installer for thorium, normally only built by a seperate flag when building, and also normally not included in the installer, but useful for debugging. I also added chromedriver.

Second thing is a question; how are you getting these? You have resolutions of the chromium logo that I cant find anywhere else on the net, and especially the svg. I couldnt find svgs for many of the browser logos you have. It's all a very useful repo, but I'm just scratching my head like how did you source some of these?

Third thing is also a question, when you make a commit saying something has been "optimized" like in the recent nodejs commit, what does that mean? Compression? Color optimization? If its compression I hope its lossless lol.

**Comment by alrra** [comment]
> just reminding you to do chromium too.

@Alex313031 Updated the title for #206 so it's clear that Chromium is also part of that discussion.

> So thanks for this project... It's all a very useful repo,

Glad you found it useful! 

> how are you getting these?... I'm just scratching my head like how did you source some of these?

It's usually one of the following:

* Search for them in different places (quite a few are actually included in the project's repository).

* They are provided by people that are involved with the project and/or work for the company that develops the browser.
  
  e.g.: 

  * #180, 
  * #119
  * #59 
  * #70 
  * #55 
 

* They are created by the community.

  e.g.: see @eoghanmurray's recent great work:

  * #202 
  * #200

> when you make a commit saying something has been "optimized" like in the recent nodejs commit, what does that mean?

Image optimization is a very complex topic that I will not go into here. 

That being said, in essence, those commits are usually related to reducing the size of the file by removing unneeded metadata and re-encoding the file in a more efficient way. 

In the case of SVGs, it's also about [reducing complexity](https://github.com/alrra/browser-logos/pull/200#issuecomment-919799333) so they are rendered faster.

> If its compression I hope its lossless

The commit message will specify if it's lossless. If it's not, I usually make sure [the difference is not noticeable](https://github.com/v8/v8.dev/pull/205).

---

Close this issue in favor of #206.

**Comment by alrra** [comment]
From https://github.com/alrra/browser-logos/issues/206#issuecomment-1041025672:

> Also, @alrra in response to my previous issue which you closed (very helpful), where did you get the chromium .svg? You provided some nice links for other browsers, but I would specifically like the source for the .svg for chromium. You can find 16px-512px of it in the chromium source, but the .svg is much more useful as it can be upscaled and downscaled, and then converted to a .png for better quality. I couldn't find anywhere else on the net where there is such a high quality .svg of chromium, so I would like to see where you actually got this.

---

> where did you get the chromium .svg?

@Alex313031 `chromium.svg` was introduced in this [commit](https://github.com/alrra/browser-logos/commit/efd02ef1cd136b10bd7885f3a139d9ddbe569ea6), but I don't remember where exactly I found it. Most probably I just used image search.

ℹ️ If, for example, you use Google image search, you can add [`filetype:svg`](https://support.google.com/webmasters/answer/35287?hl=en) to limit results to SVGs.
