### ISSUE TITLE
Edge svg doesn't open in Figma

### ISSUE THREAD

**Issue by dillingham** [alrra/browser-logos#222]
<img width="731" alt="Screenshot 2024-02-02 at 8 30 33 PM" src="https://github.com/alrra/browser-logos/assets/29180903/d1cc6872-6a36-443d-a200-4d5ad8bf03cf">

or in [svgomg](https://jakearchibald.github.io/svgomg/)

**Comment by alrra** [comment]
> or in [svgomg](https://jakearchibald.github.io/svgomg/)

@dillingham Seems to be fine in SVGOMG.

![](https://github.com/alrra/browser-logos/assets/1223565/25a974a1-5eeb-4e24-a898-ee74433505e2)

**Comment by dillingham** [comment]
@alrra not for me, nor in figma.. oh well closing
