### ISSUE TITLE
SRWare Iron

### ISSUE THREAD

**Issue by impressivewebs** [alrra/browser-logos#43]
http://www.srware.net/en/software_srware_iron.php

Doesn't seem to have a logo though and it's pretty much a Chrom clone. I suppose you could try to obtain the SRWare logo and use that.

**Comment by alrra** [comment]
Added in https://github.com/alrra/browser-logos/commit/f70ec979df3bcd28fe94f7d1a8b7f8fd3c3f3f50. 🎉
