### ISSUE TITLE
Naenara (내나라) logo

### ISSUE THREAD

**Issue by alrra** [alrra/browser-logos#58]
I was reading [this blog post](https://web.archive.org/web/20150108223420/https://blog.whitehatsec.com/north-koreas-naenara-web-browser-its-weirder-than-we-thought/) yesterday and I decided to [install](http://www.openingupnorthkorea.com/downloads-2) North Korea’s [Red Star OS](http://en.wikipedia.org/wiki/Red_Star_OS) just to see how it is. While fiddling around, I also extracted Red Star's Naenara browser logo:

<img src="https://cloud.githubusercontent.com/assets/1223565/5679256/4795f23e-9805-11e4-9410-d87008f12a0b.png" alt="Naenara browser logo" width=128 height=128>

<img src="https://cloud.githubusercontent.com/assets/1223565/5679419/eba47466-9807-11e4-9102-6335b979dc06.png" alt="North Korea’s Red Star OS"> 

Unfortunately, `128×128px` is the biggest size provided (or at least, the biggest that I could find):

<img src="https://cloud.githubusercontent.com/assets/1223565/5679418/eba0aef8-9807-11e4-96af-0357be8f7488.png" alt="North Korea’s Red Star OS">

**Comment by vladikoff** [comment]
Hah this is awesome! Great work!

**Comment by passy** [comment]
Amazing! :D

**Comment by sindresorhus** [comment]
![image](https://cloud.githubusercontent.com/assets/170270/5888678/5e496fa6-a444-11e4-9de6-50c20bfa00a7.png)

**Comment by arthurvr** [comment]
Nice Cătălin!

**Comment by sindresorhus** [comment]
![image](https://cloud.githubusercontent.com/assets/170270/5888700/018f75ac-a445-11e4-8c44-2ffd2427e86b.png)

**Comment by sindresorhus** [comment]
![giphy](https://cloud.githubusercontent.com/assets/170270/5888702/19a13130-a445-11e4-9271-1dcbfa43d787.gif)
