### ISSUE TITLE
Add logo for Microsoft Edge

### ISSUE THREAD

**Issue by alrra** [alrra/browser-logos#59]
![](https://cloud.githubusercontent.com/assets/1223565/5842233/ccfb159e-a1ab-11e4-9466-dfa66492e538.png)

See also: 

* http://blogs.msdn.com/b/ie/archive/2015/01/22/project-spartan-and-the-windows-10-january-preview-build.aspx
* https://twitter.com/ppk/status/560072947613057024

**Comment by alrra** [comment]
Closing. When the browser codenamed "Project Spartan" will be released I will reopen this issue if needed. :)

**Comment by alrra** [comment]
![](https://cloud.githubusercontent.com/assets/1223565/6796459/237590d6-d1fc-11e4-8828-5d0b6e3ad71e.png)

**Comment by jacobrossi** [comment]
Just FYI, this is a placeholder icon.  Official names and logos will follow in the future. So no need to add this quite yet ;-)

**Comment by alrra** [comment]
> So no need to add this quite yet ;-)

@jacobrossi Yes, I know, see the twitter link in my first [comment](https://github.com/alrra/browser-logos/issues/59#issue-55057011). The role of this issue if mainly to see how things evolve and track the changes.

Also, thanks for your comment, I sincerely appreciate it!

**Comment by alrra** [comment]
The name of the browser is **Microsoft Edge**

![screen shot 2015-04-29 at 20 50 44](https://cloud.githubusercontent.com/assets/1223565/7397494/83d85ebe-eeb1-11e4-9cb6-8cee14bec47a.png)

**Comment by alrra** [comment]
![Microsoft Edge browser logo](https://cloud.githubusercontent.com/assets/1223565/7398117/94c9a558-eeb5-11e4-80aa-d10785ce3b26.png)

**Comment by alrra** [comment]
![](https://cloud.githubusercontent.com/assets/1223565/7398874/864c07aa-eeba-11e4-89f6-157bd1d52f4a.jpg)

**Comment by alrra** [comment]
Microsoft Edge Logo:

* png: https://www.dropbox.com/s/cd6pvt6kvczgml9/edge-logo.png?dl=0
* svg: https://www.dropbox.com/s/idjejxdxm8wf5xn/edge-logo.svg?dl=0

Thanks to @codepo8!

(source: https://twitter.com/codepo8/status/593489653312954369)
