### ISSUE TITLE
Add WaterFox icon

### ISSUE THREAD

**Issue by kntsoft** [alrra/browser-logos#65]
Hello,

Add the WaterFox's icon browser

https://www.waterfoxproject.org/

Thanks!!!

**Comment by alrra** [comment]
The logo that is provided with the OS X version is the following:

<img src="https://cloud.githubusercontent.com/assets/1223565/6665986/8343e964-cbe8-11e4-8999-7317f2a045b4.png" width=250 height=250>

However, something doesn't seem right with it (see also the search results for: [_"WaterFox logo"_](https://www.google.com/search?hl=en&biw=1280&bih=694&gbv=2&tbm=isch&sa=1&q=WaterFox+logo&oq=WaterFox+logo&gs_l=img.3..0.736.1367.0.2111.5.4.0.1.1.0.97.343.4.4.0.msedr...0...1c.1.62.img..0.5.342.v-Zlbog9vdw))

@kntsoft, @MrAlex94 Is that above the correct logo?

--

@MrAlex94 Can you help us with a `.svg` version of the logo? Thanks!

**Comment by kntsoft** [comment]
Yes, it's the same in the Windows version.

**Comment by alrra** [comment]
> Add the WaterFox's icon browser

@kntsoft Done in https://github.com/alrra/browser-logos/commit/a75786248210ada7dfc3ee97e1a5165867b30b26.

**Comment by MrAlex94** [comment]
That's the correct logo. I can ask the designer for the SVG version if there is one, if you still need it?

**Comment by alrra** [comment]
> That's the correct logo.

@MrAlex94 Thanks for confirming! 

>  if you still need it?

@MrAlex94 Sure! :)

**Comment by kntsoft** [comment]
Thanks!!!!

**Comment by alrra** [comment]
> I can ask the designer for the SVG version if there is on

@MrAlex94 ping :)

**Comment by MrAlex94** [comment]
Sorry for the late reply everyone! The designer doesn't have any SVG versions but the logo is getting another update soon so I should be able to give you guys everything then :-)

**Comment by alrra** [comment]
> The designer doesn't have any SVG versions but the logo is getting another update soon so I should be able to give you guys everything then :-)

Thanks for the update @MrAlex94!
