### ISSUE TITLE
Add QupZilla Logo

### ISSUE THREAD

**Issue by kntsoft** [alrra/browser-logos#66]
Hello, 

I found a Browser without Logo. The browser is QupZilla.

There are the links:
Official website: www.qupzilla.com
Github link: https://github.com/QupZilla/

The logo:
![Logo of QupZilla](https://github.com/QupZilla/qupzilla/blob/v1.8/linux/hicolor/128x128/apps/qupzilla.png?raw=true)

**Comment by alrra** [comment]
@kntsoft Thanks for opening this issue, but unfortunately, I couldn't find a decent version of the logo (`512x512px` or higher). If you find one feel free to open a pull request. :)


> a Browser without Logo.

@kntsoft There are still [quite a few](https://github.com/alrra/browser-logos/issues/44) browsers for which we don't have their logos. :)

**Comment by alrra** [comment]
@kntsoft Added in https://github.com/alrra/browser-logos/commit/908f990f4ab9edf9d455cabce99077c94fe09e43. :)
