### ISSUE TITLE
Add new WebKit logo?

### ISSUE THREAD

**Issue by paulirish** [alrra/browser-logos#68]
in a new deck from WWDC there is a webkit logo!

https://developer.apple.com/videos/wwdc/2015/  "Using Safari to Deliver and Debug a Responsive Web Design"

http://devstreaming.apple.com/videos/wwdc/2015/5059xl75l59/505/505_using_safari_to_deliver_and_debug_a_responsive_web_design.pdf

![image](https://cloud.githubusercontent.com/assets/39191/8169775/b17d2e66-1360-11e5-8372-94aceb89a803.png)

**Comment by mathiasbynens** [comment]
@hober Can you help us get a high-res, or even better, an SVG version of this?

**Comment by hober** [comment]
I'll look into it.

**Comment by alrra** [comment]
> I'll look into it.

@hober Any luck?

**Comment by Krinkle** [comment]
Hm... is this authoritative though? I don't see it used on http://www.webkit.org/ – though that might just mean they don't prioritise the website.

Also worth checking whether Apple uses this as icon for the OSX WebKit framework API or also for the WebKit open source project as a whole (and by extent, the default browser build they produce).

Apple has logos most all their OSX framework APIs and this looks like one of those. It doesn't look like the logo of the WebKit project or the browser to me.

**Comment by alrra** [comment]
> Also worth checking whether Apple intended this to be the icon of the OSX WebKit framework API or also for the WebKit open source project as a whole (and by extent, the WebKit browser).
>
> Apple has logos for most all their OSX framework APIs and this looks like one of those. It doesn't look like the logo of the WebKit project or the browser to me.

@Krinkle We'll see (same as with [other browser logos](https://github.com/alrra/browser-logos/issues/59)).

---

> I don't see it used on http://www.webkit.org/ – though that might just mean they don't prioritise the website.

Note: They recently updated the profile image for the [WebKit Twitter account](https://twitter.com/webkit).

![](https://cloud.githubusercontent.com/assets/1223565/8883207/c190ffe4-3255-11e5-8ea8-b5c21376d28b.png)

--

![New WebKit logo](https://cloud.githubusercontent.com/assets/1223565/8883152/502f6e44-3255-11e5-8db7-60f2733cdef3.jpg)

**Comment by alrra** [comment]
From: https://twitter.com/webkit/status/627218318458535936

![](https://cloud.githubusercontent.com/assets/1223565/9018648/ac1b4b76-37e9-11e5-9918-85ed31b7694c.png)

**Comment by Krinkle** [comment]
Nice!

**Comment by alrra** [comment]
From https://twitter.com/webkit/status/629291123152945152

![](https://cloud.githubusercontent.com/assets/1223565/9113787/1cee44c4-3c5f-11e5-823f-3aac815f9755.png)

--

![](https://cloud.githubusercontent.com/assets/1223565/9113791/235673cc-3c5f-11e5-90d3-68ff27f07961.png)

**Comment by alrra** [comment]
(The following is mostly for me)

![](https://cloud.githubusercontent.com/assets/1223565/9119883/ce44ad5e-3c81-11e5-9691-6ec8f810ff10.png)
