### ISSUE TITLE
Operating System logos?

### ISSUE THREAD

**Issue by peterkahl** [alrra/browser-logos#69]
This browser logos collection is smashing. Thank you!

Would anyone know where to get a collection of operating systems logos?

**Comment by alrra** [comment]
> This browser logos collection is smashing. Thank you!

@peterkahl Thanks for the kind words!

> Would anyone know where to get a collection of operating systems logos?

@peterkahl I don't think there is a repository for that yet (see also: https://github.com/alrra/browser-logos/issues/52#issuecomment-65068696).

**Comment by ImanMh** [comment]
I've also been looking for OS logos and there are a tone of that on internet, but none of them has the quality of this repository. I wish you could at least do the major ones. (linux, mac, windows, android, ios)

**Comment by LukeXF** [comment]
Would be useful to see this added
