### ISSUE TITLE
Update Opera Beta and Opera Developer logos

### ISSUE THREAD

**Issue by ngyikp** [alrra/browser-logos#72]
[Opera Beta:](http://blogs.opera.com/desktop/2015/10/opera-beta-33-0-1990-35-update/)
![Opera Beta installer](http://www-static.opera.com/blogs/multi/wp-content/uploads/sites/3/2015/10/beta-inst.png)

[Opera Developer:](http://blogs.opera.com/desktop/2015/10/opera-developer-34-0-2023-0-update/)
![Opera Developer installer](http://www-static.opera.com/blogs/multi/wp-content/uploads/sites/3/2015/10/Installer-Developer.png)

**Comment by mathiasbynens** [comment]
We’ll add these logos to https://github.com/operasoftware/logo asap.
