### ISSUE TITLE
Logo matcher libraries?

### ISSUE THREAD

**Issue by Soullivaneuh** [alrra/browser-logos#77]
Do you know if some PHP / JS whatever langage libraries related to your project exists?

Some libraries that can find the corresponding log from `user-agent` string for example. (I think we can do great things with [browscap-php](https://github.com/browscap/browscap-php))

Would be great to setup a list on you Readme, what do you think?

**Comment by alrra** [comment]
> Do you know if some PHP / JS whatever langage libraries related to your project exists?

@Soullivaneuh No.

> Would be great to setup a list on you Readme, what do you think?

If there are projects that use the images from this one, sure, we can try that and see if it helps. :)
