### ISSUE TITLE
Hotlinking?

### ISSUE THREAD

**Issue by dbox** [alrra/browser-logos#78]
Do you happen to know github's current policy on hotlinking the images? I did a few searches but all the info seems old.

Thanks!

**Comment by alrra** [comment]
> hotlinking the images

@dbox If you are referring to linking to `https://raw.githubusercontent.com/...`, I personally [don't recommend it](https://github.com/alrra/browser-logos/blob/3d5bb1bcae901fbcad1885a61da76d6fe3c0ff1c/README.md#getting-the-browser-logos) because as far as I know, it is not intended as a static file hosting service.

> github's current policy on hotlinking the images

Best way to find out is to ask GitHub by sending a email to support@github.com or using the form on https://github.com/contact.

**Comment by dbox** [comment]
ok @alrra thnx for quick response!

**Comment by mathiasbynens** [comment]
@alrra could use gh-pages for everything, though, or set up a script that copies the images to the gh-pages branch on every commit (I hear there’s a nice little utility you can use for that). Then the images would be hotlinkable and nobody (not even GitHub) would get upset.

**Comment by dbox** [comment]
@mathiasbynens Thanks that's exactly what I was looking for.

I made this with @alrra 's great icons:
https://github.com/kni-labs/old-browsers

and hotlinking the images is key

**Comment by alrra** [comment]
> > could use gh-pages for everything,

> Thanks that's exactly what I was looking for.

@dbox Ah ok, I misunderstood your question.

> or set up a script that copies the images to the gh-pages branch on every commit

@mathiasbynens, @dbox The problem with that solution is that some of the [links will end up in a 404 quite fast](https://github.com/alrra/browser-logos/issues/76#issuecomment-179172631). Or, am I missing something?

**Comment by alrra** [comment]
> https://github.com/kni-labs/old-browsers
> and hotlinking the images is key

@dbox Why not use `npm` to fetch and then copy them locally?

**Comment by dbox** [comment]
The way I'm doing it shouldn't end up in 404s should it?

> @dbox Why not use npm to fetch and then copy them locally?
Npm fetch is new to me. How would that work? I think the key is that the user would just have to copy the one line of code.. super easy to implement. 
I have been trying to think about how that line of code could be dynamic via npm...
Open to better solutions!

**Comment by alrra** [comment]
> Npm fetch is new to me. How would that work? 

@dbox For example, you can do the following:

1) Install `browser-logos` as a dev dependency.

```bash
npm install --save-dev alrra/browser-logos#22.3.0
```

2) Use `npm`'s [`"scripts"` property](https://docs.npmjs.com/misc/scripts) and create a custom command to copy the logos that you need from `node_modules/browser-logos/` to your `img/` directory. 

```json
"scripts": {                                                           
  "update-browser-logos": "cp node_modules/browser-logos/*/{chrome,edge,firefox,opera,safari}_128x128.png img"
},  
```

Note: Depending on which logos you rely on, when you update to a new **major** version of `browser-logos`, you may need to update that custom command if [there are breaking changes](https://github.com/alrra/browser-logos/issues/76#issuecomment-179172631).

3) Use the custom command to update the logos from `img/`

```bash
npm run update-browser-logos
```

You can integrate that into your build process, or just run it manually when you update to a new version of the `browser-logos`. 

--

Hope this helps. :)

**Comment by dbox** [comment]
@alrra Thanks so much for the detailed instructions. That's awesome. 

I don't think it will be the ideal workflow for what i'm trying to do for [old-browsers](https://github.com/kni-labs/old-browsers), but it definitely gives me ideas for some other repos!:)

**Comment by alrra** [comment]
@dbox: The browser logos are now available via `cdnjs`: https://cdnjs.com/libraries/browser-logos.

**Comment by dbox** [comment]
Awesome. Thanks!
