### ISSUE TITLE
Add to `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [alrra/browser-logos#83]
hi, recently we want to add your lib on http://cdnjs.com, could you please tell me what files should be hosted on CDN?
thank you very much!

https://github.com/cdnjs/cdnjs/issues/7865

**Comment by alrra** [comment]
>  could you please tell me what files should be hosted on CDN?

@maruilian11 Everything **except** the following:

```
.editorconfig
.git
.gitattributes
.github
.npmignore
.scripts
archive/README.md
bower.json
CHANGELOG.md
package.json
README.md
```

--

From: https://github.com/cdnjs/cdnjs/blob/5b14dbfc41562c2d21f75d5ae1401fc6df9e9752/README.md#cdnjs-library-repository

> cdnjs will host any production version of any JavaScript/CSS library

⚠️ Do note that this is just a collection of images, it's not a JavaScript/CSS library.

(Cc: @PeterDaveHello)

--

@maruilian11, @PeterDaveHello Let me know if I can help with anything else!

**Comment by PeterDaveHello** [comment]
Images collection will be welcome. Thanks @alrra .

**Comment by maruilian11** [comment]
hi @alrra,
do you have any license for this lib?

**Comment by alrra** [comment]
> do you have any license for this lib?

@maruilian11 See: https://github.com/alrra/browser-logos#legal

**Comment by maruilian11** [comment]
thank you!

**Comment by PeterDaveHello** [comment]
@alrra I'm not sure if there will be some legal concern to host these collection publicly? Do you have any idea or comment? Thanks.

**Comment by alrra** [comment]
> I'm not sure if there will be some legal concern to host these collection publicly? Do you have any idea or comment?

@PeterDaveHello What I can tell you is that [so far](https://www.paulirish.com/2010/high-res-browser-icons/) there hasn't been any such issue with this project. Furthermore, some of the browser logos where even contributed by people that are employed by the companies that develop those browsers (e.g.: [1](https://github.com/alrra/browser-logos/issues/70), [2](https://github.com/alrra/browser-logos/pull/55)).

At the end of the day, this project isn't different from, let say, someone just using the logos in a presentation. It's only intended to help people quickly find a high resolution version of a specific logo. It doesn't, for example, use the logos in artworks that are sold or any other things that might have a negative impact or bring any losses to their owners.

**Comment by PeterDaveHello** [comment]
hmmmm ... okay, so I think we could host it!
