### ISSUE TITLE
Add Polarity logo?

### ISSUE THREAD

**Issue by Spiderpig86** [alrra/browser-logos#84]
This is just a small request for Polarity Browser.

http://polarityweb.weebly.com/

Link for image:
https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/12742747_963929246994804_4516615644568352194_n.png?oh=4bebcffb354952bb4a1d5d0907f9694e&oe=57D2853C

Thank you.

**Comment by alrra** [comment]
@Spiderpig86 Thanks! [:paperclip:](https://cloud.githubusercontent.com/assets/1223565/15799545/015c6f8a-2a69-11e6-8478-3710172008ff.png)
