### ISSUE TITLE
Publish logos individually?

### ISSUE THREAD

**Issue by alrra** [alrra/browser-logos#99]
This project has become quite big, and because most people usually only need the main browser logos, I'm thinking of publishing some of the logos separately, and therefore, transform this into a [monorepo](https://github.com/babel/babel/blob/6d82ee297eb304a1b96fca77818e03ff77ae39c4/doc/design/monorepo.md).

---

The plan is to:

1) Continue to release "global" versions and maintain a "global" `CHANGELOG.md`.

2) Publish some of the logos under the [`@browser-logos`](https://www.npmjs.com/~browser-logos) namespace.

   * `@browser-logos/<browser>` → to get the latest logo of `<browser>`.

      e.g.: [`@browser-logos/firefox`](https://github.com/alrra/browser-logos/tree/d3ae4716c4d94cfc6affc6734ced87bc41cb4045/firefox)

   * `@browser-logos/<browser>_<version_x>[-<version_y>]` → to get the logo
     used by `<version_x>`, or between `<version_x>` and `<version_y>` of `<browser>`.

      e.g.:

        * [`@browser-logos/internet-explorer_6`](https://github.com/alrra/browser-logos/tree/d3ae4716c4d94cfc6affc6734ced87bc41cb4045/archive/internet-explorer_6)
        * [`@browser-logos/internet-explorer_7-8`](https://github.com/alrra/browser-logos/tree/d3ae4716c4d94cfc6affc6734ced87bc41cb4045/archive/internet-explorer_7-8)

   Other notes:

   * [Logos for which the exact browser versions are not known](https://github.com/alrra/browser-logos/tree/59fa8f323f28d73ea1f13dc47288b2c197807a51/archive#note) won't be published as that can potentially create confusion and some problems down the line.

   * For the logos that will be publish, their directory will contain the following:

      ```
      <browser>.png
      <browser>.svg (if it exists)
      <browser>_16x16.png
      <browser>_24x24.png
      <browser>_32x32.png
      <browser>_48x48.png
      <browser>_64x64.png
      <browser>_128x128.png
      <browser>_256x256.png
      <browser>_512x512.png
      CHANGELOG.md (yes, they will get their own CHANGELOG!!)
      package.json
      README.md
      ```

---

Thoughts? :)

**Comment by mathiasbynens** [comment]
Sounds amazing, if you don’t mind the extra maintenance overhead! Hopefully tools like lerna can help here.

**Comment by alrra** [comment]
> Hopefully tools like lerna can help here.

@mathiasbynens I actually looked into `Lerna` and some other tools, but I don't think I'll need them. These packages don't have dependencies, and most of them won't get many updates, probably only patch version as the images are further optimized

> if you don’t mind the extra maintenance overhead!

When needed, I'll probably write some scripts to automate things

**Comment by alrra** [comment]
Also, this issue is done! 🎉
